services:
  kokoro-web:
    image: ghcr.io/eduardolat/kokoro-web:latest
    expose:
      - "3000"
    environment:
      - KW_SECRET_API_KEY=${KOKORO_API_KEY}
    volumes:
      - ./kokoro-cache:/kokoro/cache
    restart: unless-stopped

  backend:
    image: addibib/echodocs-backend:latest   # ✅ use pulled image
    expose:
      - "${PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - KOKORO_BASE_URL=${KOKORO_BASE_URL}
      - KOKORO_API_KEY=${KOKORO_API_KEY}
      - KOKORO_TTS_VOICE=${KOKORO_TTS_VOICE}
      - PORT=${PORT}
    depends_on:
      - kokoro-web
    restart: unless-stopped

  frontend:
    image: addibib/echodocs-frontend:latest  # ✅ use pulled image
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"   # serve frontend on port 80
    depends_on:
      - backend
    restart: unless-stopped
