version: "3.8"

services:
  kokoro-web:
    image: ghcr.io/eduardolat/kokoro-web:latest
    expose:
      - "3000"
    environment:
      - KW_SECRET_API_KEY=${KOKORO_API_KEY}
    volumes:
      - ./kokoro-cache:/kokoro/cache
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "${PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - KOKORO_BASE_URL=${KOKORO_BASE_URL}
      - KOKORO_API_KEY=${KOKORO_API_KEY}
      - KOKORO_TTS_VOICE=${KOKORO_TTS_VOICE}
      - PORT=${PORT}
    depends_on:
      - kokoro-web
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "/api"
        VITE_CLOUDINARY_CLOUD_NAME: ${VITE_CLOUDINARY_CLOUD_NAME}
        VITE_CLOUDINARY_UPLOAD_PRESET: ${VITE_CLOUDINARY_UPLOAD_PRESET}
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
